import type { MarketProduct, Venue } from "../engine/types";
import { defaultVenueMarketSettings } from "../engine/venueSettings";

export const seedVenue: Venue = {
  id: "ven_demo",
  slug: "demo-venue",
  name: "Demo Venue",
  currency: "GBP",
  timezone: "Europe/London",
  ...defaultVenueMarketSettings(),
};

export const seedProducts: MarketProduct[] = [
  {
    id: "mp_cem",
    symbol: "CEM",
    name: "Classic Espresso",
    category: "Cocktails",
    basePriceMinor: 1100,
    currentPriceMinor: 1100,
    floorPriceMinor: 800,
    ceilingPriceMinor: 1800,
    salesVelocity: 8,
    isLive: true,
    isSoldOut: false,
    priority: true,
  },
  {
    id: "mp_cmar",
    symbol: "CMAR",
    name: "Classic Margarita",
    category: "Cocktails",
    basePriceMinor: 1200,
    currentPriceMinor: 1200,
    floorPriceMinor: 800,
    ceilingPriceMinor: 1800,
    salesVelocity: 5,
    isLive: true,
    isSoldOut: false,
    priority: false,
  },
  {
    id: "mp_t75",
    symbol: "T75",
    name: "The 75th Peel",
    category: "Cocktails",
    basePriceMinor: 1200,
    currentPriceMinor: 1200,
    floorPriceMinor: 900,
    ceilingPriceMinor: 1800,
    salesVelocity: 3,
    isLive: true,
    isSoldOut: false,
    priority: false,
  },
  {
    id: "mp_wb",
    symbol: "WB",
    name: "Woodland Bloom",
    category: "Mocktails",
    basePriceMinor: 800,
    currentPriceMinor: 800,
    floorPriceMinor: 600,
    ceilingPriceMinor: 1100,
    salesVelocity: 2,
    isLive: true,
    isSoldOut: false,
    priority: false,
  },
  {
    id: "mp_negroni",
    symbol: "NEG",
    name: "Classic Negroni",
    category: "Cocktails",
    basePriceMinor: 1100,
    currentPriceMinor: 1100,
    floorPriceMinor: 800,
    ceilingPriceMinor: 1650,
    salesVelocity: 7,
    isLive: true,
    isSoldOut: false,
    priority: false,
  },
  {
    id: "mp_spritz",
    symbol: "SPZ",
    name: "Aperol Spritz",
    category: "Cocktails",
    basePriceMinor: 1200,
    currentPriceMinor: 1200,
    floorPriceMinor: 900,
    ceilingPriceMinor: 1800,
    salesVelocity: 2,
    isLive: true,
    isSoldOut: false,
    priority: false,
  },
  {
    id: "mp_mojito",
    symbol: "MOJ",
    name: "Sarti Spritz",
    category: "Cocktails",
    basePriceMinor: 1000,
    currentPriceMinor: 1000,
    floorPriceMinor: 750,
    ceilingPriceMinor: 1500,
    salesVelocity: 6,
    isLive: true,
    isSoldOut: false,
    priority: false,
  },
  {
    id: "mp_old",
    symbol: "OLD",
    name: "Old Fashioned",
    category: "Cocktails",
    basePriceMinor: 1300,
    currentPriceMinor: 1300,
    floorPriceMinor: 1000,
    ceilingPriceMinor: 1950,
    salesVelocity: 3,
    isLive: true,
    isSoldOut: false,
    priority: false,
  },
  {
    id: "mp_bloody",
    symbol: "BLD",
    name: "Classic Bloody Mary",
    category: "Cocktails",
    basePriceMinor: 1300,
    currentPriceMinor: 1300,
    floorPriceMinor: 1000,
    ceilingPriceMinor: 1950,
    salesVelocity: 4,
    isLive: true,
    isSoldOut: false,
    priority: false,
  },
];
